/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_common_bassdiff_BassdiffUtils */

#ifndef _Included_com_example_common_bassdiff_BassdiffUtils
#define _Included_com_example_common_bassdiff_BassdiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_common_bassdiff_BassdiffUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_common_bassdiff_BassdiffUtils_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_example_common_bassdiff_BassdiffUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_common_bassdiff_BassdiffUtils_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
