/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_common_jpeg_CompressUtil */

#ifndef _Included_com_example_common_jpeg_CompressUtil
#define _Included_com_example_common_jpeg_CompressUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_common_jpeg_CompressUtil
 * Method:    compressBitmap
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_common_jpeg_CompressUtil_compressBitmap
        (JNIEnv *, jclass,jobject ,jint, jstring);

#ifdef __cplusplus
}
#endif
#endif